# Generated by Django 3.2.7 on 2021-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='anons'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(verbose_name='pub_date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='full_tetx',
            field=models.TextField(verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
