# Generated by Django 3.2.7 on 2021-09-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_article_full_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='full_tetx',
            new_name='full_text',
        ),
    ]
